### ISSUE TITLE
aha

### ISSUE THREAD

**Issue by see-ocean** [Discord-js-Polska/shadow#1]
Co robi w tytule słowo autorski?

**Comment by see-ocean** [comment]
*nazwie commita

**Comment by kacperrrooo** [comment]
Shadow syfek es

**Comment by kacperrrooo** [comment]
Nie ma podjazdu do miltona

**Comment by see-ocean** [comment]
No i masz rację, i dokończmy temat

**Comment by kacperrrooo** [comment]
No nie ma o czym gadać jak ten bot jest na example z d.js

**Comment by xFizzydev** [comment]
no chyba on jest twojego autorstwa cnie ale wedlug package.json to nie wynika
na przyszlosc dodaj licencje do package + authora

**Comment by see-ocean** [comment]
Nie mówię o licencji, tylko o nazwie commitu
![obraz](https://user-images.githubusercontent.com/47253870/94574850-e0be6200-0273-11eb-950b-ce6f61ad7875.png)

**Comment by xFizzydev** [comment]
tu masz bota jak bys chcial robic reklamowego: https://github.com/kacperrrooo/marketing

**Comment by cymerek** [comment]
Eee chciałbym tylko powiedzieć hujtas
